name: MECKA
favicon: null
layout_spectrum: 0.42294220556505024
typography_spectrum: 0.6258606768678874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  brandStrength: 0.27285425551235676
  lightness: 0.5207864381372929
  saturation: 0.7830160376615822
  rhythmicContrast: 0.7191142472438514
purpose: []
