name: MECKA
favicon: null
layout_spectrum: 0.24773
typography_spectrum: 0.4525416570249945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.14887803210876882
  lightness: 0.15588068636134267
  saturation: 0.3505594728048891
  rhythmicContrast: 0.5571102283429354
purpose: []
