name: MECKA
favicon: null
layout_spectrum: 0.17376
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c5cf65'
    - '#0e1b07'
    - '#5c8119'
    - '#274309'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
