name: MECKA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4dde6'
    - '#070709'
    - '#56514e'
    - '#9eb0bc'
    - '#636d65'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
